const sentences: string[] = [
    "In the labyrinth of codes, the secret is hidden in plain sight.",
    "Every cipher tells a story, waiting for the key to unlock its meaning.",
    "The encrypted message shimmered like a hidden gem in the digital realm.",
    "A master of cryptography leaves clues in every character.",
    "Through the art of decryption, mysteries unfold one byte at a time.",
    "The puzzle's complexity challenged even the sharpest minds.",
    "Hidden patterns in numbers reveal secrets to those who listen.",
    "A code is only as strong as its key, and every key holds promise.",
    "The delicate dance of algorithms transforms gibberish into meaning.",
    "Mathematics and mystery merge in the world of encryption.",
    "Each symbol in the cipher has a role in the unfolding mystery.",
    "When bits and bytes align, the hidden message comes to life.",
    "The cryptogram required both logic and creativity to solve.",
    "Digital secrets are safeguarded behind layers of complex algorithms.",
    "The challenge was simple yet profound—a test of both wit and patience.",
    "Unlocking the code demanded a blend of mathematics and intuition.",
    "Every encrypted text holds the promise of a hidden truth.",
    "A riddle wrapped in a cipher awaits the keen mind.",
    "The key to success lies in deciphering the complex puzzle.",
    "Through diligent analysis, the obscure patterns begin to emerge.",
    "Intricate codes require a deep understanding of cryptography.",
    "The challenge was set: decode the mystery before time ran out.",
    "A series of encrypted messages formed a trail of digital breadcrumbs.",
    "Every cipher hides a secret message waiting to be revealed.",
    "The puzzle's encryption combined historical techniques with modern twists.",
    "Numbers, letters, and symbols coalesce into a complex riddle.",
    "Cracking the code meant seeing beyond the obvious characters.",
    "Each decryption step brought the hidden message closer to light.",
    "An enigma wrapped in layers of cryptography challenged every participant.",
    "The mystery was encoded using techniques that spanned centuries.",
    "A mind attuned to detail could unravel even the most intricate ciphers.",
    "Deciphering the cryptogram was like unlocking a digital safe.",
    "The process of decryption required both analytical and creative thinking.",
    "Every challenge was a journey through the fascinating world of codes.",
    "The secret message lay hidden within a cascade of random symbols.",
    "Ciphers have a way of concealing truth in plain sight.",
    "Decryption is the art of turning chaos into clarity.",
    "The encrypted challenge was a puzzle that promised a reward for perseverance.",
    "Underneath layers of encryption, a simple truth awaited discovery.",
    "Every character in the code played a vital role in the hidden narrative.",
    "Decoding the message required both precision and imagination.",
    "Complex algorithms masked a simple, yet profound message.",
    "The cipher was a digital maze designed to challenge the intellect.",
    "Each step in the decryption process unveiled another layer of mystery.",
    "The challenge lay in discerning order within the chaos of the code.",
    "Mathematics served as the key to unlocking a world of encrypted secrets.",
    "The intricacies of the cipher reflected the depth of the challenge.",
    "Every successful decryption reveals a piece of the larger puzzle.",
    "The enigma was encoded using a blend of traditional and modern techniques.",
    "Every step toward decryption was a leap into the unknown.",
    "Decrypting the cipher was a journey into the heart of encryption.",
    "The hidden message was woven into the fabric of the code.",
    "Every challenge in the cipher required careful analysis and creative thought.",
    "Decrypting the message revealed a story encoded in numbers and letters.",
    "The puzzle was encrypted with techniques that made every step of decryption rewarding.",
    "Decrypting the code was like deciphering the language of secrets.",
    "Each step in solving the cipher was like peeling back layers of digital mystery.",
    "The cipher was a labyrinth designed to test your problem-solving skills.",
    "Every encrypted clue was a stepping stone to the final revelation.",
    "Decrypting required precision, logic, and a dash of creativity.",
    "The encrypted text concealed a narrative that slowly came to light with each decryption.",
    "Every successful decode revealed a fragment of a hidden story.",
    "The puzzle was a cryptographic challenge that demanded both accuracy and intuition.",
    "Decrypting the cipher was a blend of scientific rigor and artistic insight.",
    "Each encrypted message was like a riddle wrapped in a mystery.",
    "The challenge was hidden in plain sight, waiting for the right key to unlock it.",
    "Every decryption attempt brought new insights into the encrypted world.",
    "The cipher was an elegant mix of art and science, designed to test your skills.",
    "Decrypting revealed the hidden structure behind seemingly random characters.",
    "Each puzzle within the cipher was a window into the intricacies of encryption.",
    "The encrypted message challenged you to look beyond the surface.",
    "Every successful decryption was a victory in the battle against encryption.",
    "The cipher was constructed with layers of encryption, each adding to the challenge.",
    "Decrypting the code was a meticulous process of uncovering hidden patterns.",
    "The encrypted message was a masterpiece of coded design.",
    "Every step of decryption required you to combine logic with creativity.",
    "The cipher held secrets that only the determined could unveil.",
    "Decrypting the message required an analytical mind and a keen eye for detail.",
    "Each encrypted piece was a puzzle in its own right, waiting to be solved.",
    "The challenge was to decode the labyrinth of symbols to reveal the underlying message.",
    "Every step in deciphering the code brought you closer to a hidden truth.",
    "The cipher was a mystery wrapped in layers of digital complexity.",
    "Decrypting the code was a journey into the heart of digital encryption.",
    "Each successful decryption illuminated a new fragment of the puzzle.",
    "The cryptographic challenge invited you to explore the depths of hidden messages.",
    "Every encrypted symbol was a hint pointing toward the ultimate solution.",
    "Decrypting the code was a blend of logic, intuition, and perseverance.",
    "The cipher was an enigmatic challenge that rewarded persistence and sharp thinking.",
    "Decrypting transformed a jumble of symbols into a coherent story.",
    "Every decrypted word added clarity to the hidden message.",
    "The cipher tested your ability to spot patterns in chaos.",
    "Each step in deciphering was a puzzle piece forming the complete picture.",
    "Decrypting was a meticulous process of unraveling a coded narrative.",
    "Every encrypted word was a testament to the power of cryptography.",
    "The cipher was designed to hide secrets within layers of encryption.",
    "Decrypting required a combination of technical skill and creative thought.",
    "Every decoded message revealed another piece of the hidden puzzle.",
    "The encrypted text was a challenge meant for the most persistent problem solvers.",
    "Each decryption success brought you closer to the ultimate secret.",
    "Decrypting the cipher was like uncovering a hidden treasure of information.",
    "Every part of the code was a clue waiting to be interpreted correctly.",
    "The challenge was to reveal the secret concealed within the code.",
    "Each decryption trial was a step closer to unlocking the cryptographic mystery.",
    "Decrypting transformed an obscure sequence of symbols into a clear, meaningful message.",
    "Every part of the cipher contributed to the final, meaningful message.",
    "The challenge lay in deciphering the complex structure behind the encryption.",
    "Decrypting the code was a meticulous process of uncovering hidden patterns.",
    "Every decoded clue added depth to the overarching secret.",
    "The cipher was designed to challenge your understanding of cryptography.",
    "Each step of decryption was a testament to your problem-solving abilities.",
    "The puzzle invited you to dive deep into the realm of cryptography.",
    "Every encrypted symbol was a hint pointing toward the ultimate solution.",
    "Decrypting the code was a blend of logic, intuition, and perseverance.",
    "The cipher was an intricate dance of numbers and letters waiting to be deciphered.",
    "Each successful decryption step was a victory against the complexity of the cipher.",
    "The hidden message emerged gradually as you decoded the complex cipher.",
    "Every part of the code was a clue waiting to be interpreted correctly.",
    "The challenge was to reveal the secret concealed within the code.",
    "Each decryption trial was a step closer to unlocking the cryptographic mystery.",
    "Decrypting transformed a jumble of symbols into a coherent story.",
    "Every decrypted message was a window into the art of encryption.",
    "The cipher tested your ability to spot patterns in chaos.",
    "Each step in deciphering was a puzzle piece forming the complete picture.",
    "Decrypting was a meticulous process of unraveling a coded narrative.",
    "Every encrypted word was a testament to the power of cryptography.",
    "The cipher was designed to hide secrets within layers of encryption.",
    "Decrypting required a combination of technical skill and creative thought.",
    "Every decoded message revealed another piece of the hidden puzzle.",
    "The encrypted text was a challenge meant for the most persistent problem solvers.",
    "Each decryption success brought you closer to the ultimate secret.",
    "Decrypting the cipher was like uncovering a hidden treasure of information.",
    "Every part of the code was a clue waiting to be interpreted correctly."
];

const keys: string[] = [
    "quick", "lazy", "happy", "sad", "bright",
    "dark", "cool", "warm", "gentle", "loud",
    "fox", "dog", "cat", "mouse", "bird",
    "lion", "tiger", "bear", "wolf", "eagle",
    "shark", "whale", "horse", "monkey", "panda",
    "koala", "zebra", "giraffe", "elephant", "leopard"
];

const getAlgorithm = (algortihms: [String]) => {
    //randomly picks an element from the algortihms array
    const randAlgo = Math.floor(Math.random() * algortihms.length);

    return algortihms[randAlgo];
}

const getSentence = () => {
    //randomly picks an element from the algortihms array
    const randSentence = Math.floor(Math.random() * sentences.length);

    return sentences[randSentence];
}

const getKey = () => {
    //randomly picks an element from the algortihms array
    const randSentence = Math.floor(Math.random() * sentences.length);

    return sentences[randSentence];
}

export default { getAlgorithm, getSentence, getKey };